version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: dockerfile
    image: ml:v1
    container_name: ml
    command: [ "sleep", "30d" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - 8086:80